### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by soulspark666** [maple3142/saucenao-search-tgbot#8]
I tried to deploy it as it is told but it is showing some errors.
![error](https://user-images.githubusercontent.com/37495396/66824106-19680d00-ef37-11e9-8cca-279003ff765e.PNG)

Please Help

**Comment by maple3142** [comment]
You have to correctly configure your `.env` file first:
```
SAUCENAO_APIKEY=
TG_TOKEN=
HOST=127.0.0.1
WEBHOOK_URL=
DEBUG=saucenao-tg:*
DATABASE_URL=
MINIUM_SIMILARITY=50
MAX_RESULT_COUNT=3
```

It is because your `WEBHOOK_URL` is empty, and it has to be some URL that is publicly accessible through the Internet. For example, `http://your.domain.com` or `http://123.45.67.89` is okay.

**Comment by soulspark666** [comment]
Is the bot that you have given (@SauceNAO_Search_bot), working???

**Comment by maple3142** [comment]
> Will 127.0.0.1 work as WEBHOOK_URL??

`http://127.0.0.1` is a valid WEBHOOK_URL but it won't work since `127.0.0.1` points to your local computer.
WEBHOOK_URL should be an address that can be used to connect to the server on your computer.

**Comment by soulspark666** [comment]
Can https://doc-robot.000webhostapp.com/ be used as WEBHOOK_URL???
If not what can be used!!

**Comment by maple3142** [comment]
WEBHOOK_URL should points to a server running this Telegram bot, and the URL you provided is a free PHP hosting, so it won't work.
I don't know where would you host this bot.

**Comment by soulspark666** [comment]
I am running it on my pc. and trying to access it via my telegram.

**Comment by soulspark666** [comment]
Can you tell me if @SauceNAO_Search_bot is working??
Because last time I tried it, it did not give any reply.

**Comment by maple3142** [comment]
> Can you tell me if @SauceNAO_Search_bot is working??

Yes, it is working.

**Comment by soulspark666** [comment]
> 
> 
> I am running it on my pc. and trying to access it via my telegram.
> Please Can you give proper instructions on where I can deploy it???

**Comment by maple3142** [comment]
Besides, there is another way to easily run your bot on your PC, but it is less efficient.
Simple replace [this line](https://github.com/maple3142/saucenao-search-tgbot/blob/master/src/index.ts#L20) with `polling: true`, and it should work.

**Comment by soulspark666** [comment]
> 
> 
> I would recommend you to do some research in "Whats is server, ip, domain, http...", since it is too hard to explain these things to people who without these concepts.

I am trying to deploy it on heroku, so what should I add in the WEBHOOK_URL now.

I am little aware of server, ip, and domain, but I am still new to this. Please help me.

**Comment by soulspark666** [comment]
> 
> 
> Besides, there is another way to easily run your bot on your PC, but it is less efficient.
> Simple replace [this line](https://github.com/maple3142/saucenao-search-tgbot/blob/master/src/index.ts#L20) with `polling: true`, and it should work.

I tried this sollution.
Here is the output to it, but I was not getting answers to it.


```
C:\Users\anime\Desktop\New Pull\saucenao-search-tgbot>yarn start
yarn run v1.19.1
$ tsc && node dist/index.js
Unhandled rejection Error: EFATAL: WebHook and Polling are mutually exclusive
    at TelegramBot.openWebHook (C:\Users\anime\Desktop\New Pull\saucenao-search-tgbot\node_modules\node-telegram-bot-api\src\telegram.js:433:29)
    at Object.<anonymous> (C:\Users\anime\Desktop\New Pull\saucenao-search-tgbot\dist\index.js:19:5)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11

(node:16400) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)
(node:16400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

![Capture](https://user-images.githubusercontent.com/37495396/66834186-b3868000-ef4c-11e9-8cd4-3235bd4faf36.PNG)

As you can see there is no reply from the bot.

**Comment by maple3142** [comment]
> > Besides, there is another way to easily run your bot on your PC, but it is less efficient.
> > Simple replace [this line](https://github.com/maple3142/saucenao-search-tgbot/blob/master/src/index.ts#L20) [](/maple3142/saucenao-search-tgbot/blob/HEAD@{2019-10-15T13:07:58Z}/src/index.ts#L20) with `polling: true`, and it should work.
> 
> I tried this sollution.
> Here is the output to it, but I was not getting answers to it.

You should also remove [these lines](https://github.com/maple3142/saucenao-search-tgbot/blob/master/src/index.ts#L23-L26) too.

> As you can see there is no reply from the bot but the script shows an answer.

Have you configure `DATABASE_URL`?

**Comment by maple3142** [comment]
> > I would recommend you to do some research in "Whats is server, ip, domain, http...", since it is too hard to explain these things to people who without these concepts.
> 
> I am trying to deploy it on heroku, so what should I add in the WEBHOOK_URL now.
> 
> I am little aware of server, ip, and domain, but I am still new to this. Please help me.

On heroku, WEBHOOK_URL and HOST should be `your-app-name.herokuapp.com`.

**Comment by soulspark666** [comment]
> 
> 
> Have you configure `DATABASE_URL`?
Nope, what should I add there!!??

**Comment by maple3142** [comment]
> > Have you configure `DATABASE_URL`?
> 
> Nope, what should I add there!!??

You will need a PostgreSQL database, and fill in the corresponding values into the following string.
`postgresql://DB_USER:DB_USER_PASS@DB_URL:DB_PORT/DB_NAME`

**Comment by soulspark666** [comment]
While using the offline deployment, with your suggested changes, I added the postgresql url in the DATABASE_URL part but it is still not replying to the sent images, similar to your _@SauceNAO_Search_bot_
![Capture](https://im6.ezgif.com/tmp/ezgif-6-f6d9796fcba5.gif)

**Comment by maple3142** [comment]
@SauceNAO_Search_bot works for me though: https://streamable.com/0w1uo

**Comment by soulspark666** [comment]
> 
> 
> @SauceNAO_Search_bot works for me though: https://streamable.com/0w1uo

I even tried sending it the same photo, still no reply!!
![Capture](https://user-images.githubusercontent.com/37495396/66843605-8510a100-ef5c-11e9-8c49-3296ab447544.PNG)

**Comment by soulspark666** [comment]
I tried to deploy the app on heroku, it is not replying not even to /start command!!
Here is the log for deploying
https://hastebin.com/gisepomofa.makefile

_Please help me deploy it and I will be glad to make a beginners guide for this repo._

**Comment by maple3142** [comment]
> > @SauceNAO_Search_bot works for me though: [streamable.com/0w1uo](https://streamable.com/0w1uo)
> 
> I even tried sending it the same photo, still no reply!!
> ![Capture](https://user-images.githubusercontent.com/37495396/66843605-8510a100-ef5c-11e9-8c49-3296ab447544.PNG)

Could you use https://t.me/jsondumpbot and give me the result? If you think that is private, you could simply PM the result to [me](https://t.me/maple3142). I'd like to find what happens when you try to send photo to my bot.

**Comment by soulspark666** [comment]
I have created .env file and filled in all the info..
![Capture](https://user-images.githubusercontent.com/37495396/66854570-1c7fef00-ef71-11e9-9cd9-7fae0c60db48.PNG)
As you can see in the image above

**Comment by soulspark666** [comment]
These were the logs from the heroku
```
2019-10-15T13:29:59+00:00 app[api]: Build started by user soulspark@mail.ru
2019-10-15T13:30:17.590954+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-15T13:30:16.694121+00:00 app[api]: Release v4 created by user soulspark@mail.ru
2019-10-15T13:30:16.694121+00:00 app[api]: Deploy 9d0a2fbb by user soulspark@mail.ru
2019-10-15T13:30:19.821881+00:00 heroku[web.1]: Starting process with command `npm start`
2019-10-15T13:30:20+00:00 app[api]: Build succeeded
2019-10-15T13:30:22.924911+00:00 heroku[web.1]: Process exited with status 1
2019-10-15T13:30:23.010728+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-15T13:30:23.014221+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-15T13:30:22.827192+00:00 app[web.1]:
2019-10-15T13:30:22.827213+00:00 app[web.1]: > saucenao-search-tgbot@1.0.0 start /app
2019-10-15T13:30:22.827215+00:00 app[web.1]: > tsc && node dist/index.js
2019-10-15T13:30:22.827217+00:00 app[web.1]:
2019-10-15T13:30:22.835825+00:00 app[web.1]: sh: 1: tsc: not found
2019-10-15T13:30:22.842899+00:00 app[web.1]: npm ERR! file sh
2019-10-15T13:30:22.843524+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-10-15T13:30:22.84389+00:00 app[web.1]: npm ERR! errno ENOENT
2019-10-15T13:30:22.844391+00:00 app[web.1]: npm ERR! syscall spawn
2019-10-15T13:30:22.846311+00:00 app[web.1]: npm ERR! saucenao-search-tgbot@1.0.0 start: `tsc && node dist/index.js`
2019-10-15T13:30:22.846511+00:00 app[web.1]: npm ERR! spawn ENOENT
2019-10-15T13:30:22.846869+00:00 app[web.1]: npm ERR!
2019-10-15T13:30:22.847139+00:00 app[web.1]: npm ERR! Failed at the saucenao-search-tgbot@1.0.0 start script.
2019-10-15T13:30:22.847395+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-15T13:30:22.856546+00:00 app[web.1]:
2019-10-15T13:30:22.856851+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-10-15T13:30:22.857075+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-10-15T13_30_22_849Z-debug.log
2019-10-15T13:30:25.705218+00:00 heroku[web.1]: Starting process with command `npm start`
```

Please tell me what is the problem with it!

**Comment by soulspark666** [comment]
These were the logs from the heroku
```
2019-10-15T13:29:59+00:00 app[api]: Build started by user soulspark@mail.ru
2019-10-15T13:30:17.590954+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-15T13:30:16.694121+00:00 app[api]: Release v4 created by user soulspark@mail.ru
2019-10-15T13:30:16.694121+00:00 app[api]: Deploy 9d0a2fbb by user soulspark@mail.ru
2019-10-15T13:30:19.821881+00:00 heroku[web.1]: Starting process with command `npm start`
2019-10-15T13:30:20+00:00 app[api]: Build succeeded
2019-10-15T13:30:22.924911+00:00 heroku[web.1]: Process exited with status 1
2019-10-15T13:30:23.010728+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-15T13:30:23.014221+00:00 heroku[web.1]: State changed from crashed to starting
2019-10-15T13:30:22.827192+00:00 app[web.1]:
2019-10-15T13:30:22.827213+00:00 app[web.1]: > saucenao-search-tgbot@1.0.0 start /app
2019-10-15T13:30:22.827215+00:00 app[web.1]: > tsc && node dist/index.js
2019-10-15T13:30:22.827217+00:00 app[web.1]:
2019-10-15T13:30:22.835825+00:00 app[web.1]: sh: 1: tsc: not found
2019-10-15T13:30:22.842899+00:00 app[web.1]: npm ERR! file sh
2019-10-15T13:30:22.843524+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-10-15T13:30:22.84389+00:00 app[web.1]: npm ERR! errno ENOENT
2019-10-15T13:30:22.844391+00:00 app[web.1]: npm ERR! syscall spawn
2019-10-15T13:30:22.846311+00:00 app[web.1]: npm ERR! saucenao-search-tgbot@1.0.0 start: `tsc && node dist/index.js`
2019-10-15T13:30:22.846511+00:00 app[web.1]: npm ERR! spawn ENOENT
2019-10-15T13:30:22.846869+00:00 app[web.1]: npm ERR!
2019-10-15T13:30:22.847139+00:00 app[web.1]: npm ERR! Failed at the saucenao-search-tgbot@1.0.0 start script.
2019-10-15T13:30:22.847395+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2019-10-15T13:30:22.856546+00:00 app[web.1]:
2019-10-15T13:30:22.856851+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2019-10-15T13:30:22.857075+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2019-10-15T13_30_22_849Z-debug.log
2019-10-15T13:30:25.705218+00:00 heroku[web.1]: Starting process with command `npm start`
```

Please tell me what is the problem with it!

**Comment by maple3142** [comment]
Your `.env` is probably not committed to heroku as it is in `.gitignore`. You may need to remove it from `.gitignore`.
Besides, heroku's environment makes package managers to install production dependencies by default, so devDependencies are getting ignored. You could go to app setting page on heroku and add a Config Vars `YARN_PRODUCTION` and its value is `false`.

**Comment by soulspark666** [comment]
I am still getting the same error, as the one I sent on your PM.
`2019-10-16T04:19:55.808865+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="//bot9525:AAHIdNbDlVNpka1bjGU4OSYttOc1o" host=saucenao.herokuapp.com request_id=f0d1d632-cae5-470c-b8ea-9becc4653086 fwd="91.108.6.119" dyno= connect= service= status=503 bytes= protocol=https`

As I searched for solutions I came across [this](https://stackoverflow.com/questions/14322989/first-heroku-deploy-failed-error-code-h10). Is this, the solution to my problem or there is something else.

This is what is there in my [.gitignore](https://hastebin.com/ahokemayon.shell) now.

**Comment by maple3142** [comment]
> This is what is there in my [.gitignore](https://hastebin.com/ahokemayon.shell) now.

![](https://i.imgur.com/NQpj4bR.png)
`.env` is still being ignored...

**Comment by soulspark666** [comment]
Removed that too

**Comment by soulspark666** [comment]
Also there is some settings called Webhook in heroku
![Screenshot_2019-10-16 saucenao · Webhooks Heroku](https://user-images.githubusercontent.com/37495396/66896438-4e7e6900-efe4-11e9-9b16-675691d07c0b.png)

Do I have to do something here!!??

**Comment by maple3142** [comment]
> Also there is some settings called Webhook in heroku
> ![Screenshot_2019-10-16 saucenao · Webhooks Heroku](https://user-images.githubusercontent.com/37495396/66896438-4e7e6900-efe4-11e9-9b16-675691d07c0b.png)
> 
> Do I have to do something here!!??

No, it has nothing to do with this at all.

**Comment by soulspark666** [comment]
Now the bot is replying to my messages but its not giving results to me. Similar to what was happening to your bot yesterday!

[Heroku Logs](https://hastebin.com/naxerupuwo.http)

**Comment by maple3142** [comment]
Follow [this](https://devcenter.heroku.com/articles/heroku-postgresql#set-up-postgres-on-windows) and run `heroku psql -a YOUR_APP_NAME -c "CREATE TABLE userdata (uid VARCHAR(20),min_similarity int,max_result_count int);"`

**Comment by soulspark666** [comment]
Thanks man, its now working. I will push a PR regarding a detailed deployment for noobs like me, so that other people can also use this app without any error.
